### ISSUE TITLE
Bug in image_sample.py

### ISSUE THREAD

**Issue by jonasricker** [jychoi118/P2-weighting#1]
Hi, first of all thanks a lot for sharing your code!

I believe that in `image_sample.py` the line `count += 1` (possibly in line 88) is missing, because otherwise subsequent batches will always overwrite the first batch, and sampling will run forever.

https://github.com/jychoi118/P2-weighting/blob/f0ae8b723459d9978567b27e13eaad097b42cf60/scripts/image_sample.py#L65

Kind regards, Jonas

**Comment by jychoi118** [comment]
Yes, adding `count+=1` in line 88 will solve the problem. Thank you for the notice!
