### ISSUE TITLE
Use CUDA_VISIBLE_DEVICES=x

### ISSUE THREAD

**Issue by moonnnpie** [jychoi118/P2-weighting#18]
Thanks a lot for this work. But when I use CUDA_VISIBLE_DEVICES=x, it still works on GPU 0. That's why

**Comment by linghuyuhangyuan** [comment]
You can modify `os.environ["CUDA_VISIBLE_DEVICES"] = f"{MPI.COMM_WORLD.Get_rank() % GPUS_PER_NODE}"` to `os.environ["CUDA_VISIBLE_DEVICES"] = "1"` (guided_diffusion/dist_util.py line 27). 
It's a "rude" method, but it works.

**Comment by moonnnpie** [comment]
Thanks a lot!
