### ISSUE TITLE
About training on FFHQ

### ISSUE THREAD

**Issue by Suimingzhe** [jychoi118/P2-weighting#4]
Thanks for your work.

I have two questions for training p2-weighting on FFHQ dataset.
1. Is it correct to set p2_gamma = 1 and p2_k = 1 for training face dataset (FFHQ) ?
2. I notice you choose a lightweight unet based on ADM.  Do you think using a larger-scale unet will further improve the quality of  generated fake face images? If so, which hyperparameters should I modify？

Thanks again and look forward to your reply.

Kind Regards

**Comment by jychoi118** [comment]
1. We used  p2_gamma = 0.5 and p2_k = 1 for FFHQ. However, it is okay to use p2_gamma = 1.
2. Self-attention seems to be effective in datasets (FFHQ) where global consistency is important. You may try self-attention at multiple resolutions: `--attention_resolutions 8,16,32`
