### ISSUE TITLE
FID score for FFHQ

### ISSUE THREAD

**Issue by napCC** [jychoi118/P2-weighting#6]
I tried to reimplement the FID score for FFHQ by using code from [torch-fidelity](https://github.com/toshas/torch-fidelity). However, the score is higher than the paper mentioned. I notice the [evaluations](https://github.com/jychoi118/P2-weighting/tree/main/evaluations) folder does not have the FFHQ reference batch. Can you please provide the fid score code and the real image used in the evaluation?

**Comment by jychoi118** [comment]
We measured FID scores with [clean-fid](https://github.com/GaParmar/clean-fid)
First install the library: `pip install clean-fid`
The, you can measure FID for FFHQ by running: 
`from cleanfid import fid`
`score = fid.compute_fid(fdir, dataset_name="FFHQ", dataset_res=256, dataset_split="trainval70k")`
You should put the directory of your samples in `fdir`.

**Comment by napCC** [comment]
Thanks
